name: Run JUnit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "EST"
          timezoneMacos: "EST"
          timezoneWindows: "EST"
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clear cache
        run: mvn clean install -U
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
